title: Bless Fertigkeiten Baum
description: Bless Online Haltungen, Rotationen and Fertigkeiten
theme: jekyll-theme-midnight
root: 'Bless-Skill-Tree'
google_analytics: UA-40498224-2

author:
  name: Dominic Wroblewski
  twitter: domness

twitter:
  username: domness

exclude:
  - README.md
  - package.json
  - .gitignore
  - Gemfile
  - test

timezone: Europe/London
