title: Bless Fertigkeiten Baum
description: Bless Online Haltungen, Rotationen and Fertigkeiten
theme: jekyll-theme-midnight
root: 'Bless-Fertigkeiten-Baum'
google_analytics: UA-40498224-2

author:
  name: Sascha Kätterer

exclude:
  - README.md
  - package.json
  - .gitignore
  - Gemfile
  - test

timezone: Europe/London
